server:
  port: 8080
  context-path: /cxf

cxf:
  path: /api
  jaxrs:
#    component-scan: true
      client :
        classes-scan-packages : org.apache.cxf.jaxrs.swagger
  log:
    request : true

spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/cxf_basic_secured_test
    username : root
    password : P@ssw0rd
  jpa:
    show-sql: true
    properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
            # Hibernate ddl auto (create, create-drop, validate, update)
            ddl-auto : create-drop
